version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  terraform: circleci/terraform@3.1.0

workflows:
#   test-deploy:
#     jobs:
#       - test
#   scheduled:
#     triggers:
#       - schedule:
#           cron: "0 * * * *"
#           filters:
#             branches:
#               only:
#                 - master
#     jobs:
#       - test
  test-tf:
    jobs:
#       - terraform/apply:
#           checkout: true
#           path: ./deploy
      - aws-ecr/build-and-push-image:
          repo: test
       

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
